# 使用するベースイメージを指定
FROM node:16

# コンテナ内の作業ディレクトリを作成
WORKDIR /usr/src/app

# イメージにファイルやフォルダをコピーする(プロジェクトのルートディレクトリ起点)
COPY package.json ./

# コンテナで実行するコマンド
RUN npm install

# 残りのアプリケーションファイルをコピー
COPY . .

# コンテナ起動時に実行するコマンド
CMD ["npm", "start"]





